### ISSUE TITLE
Trying run a Multiplayer server

### ISSUE THREAD

**Issue by sethsalieri** [WTFGeeks/Natural-Magic#109]
Basically my friend runs a multiplayer server he has 8 GB of RAM he allocated 4 for the game. But its severely unplayable and it rubberbands very frequently. Are we doing something wrong? Do we use hamachi to run it or something else perhaps? any tips?

We also downloaded the server stuff from the AT launcher itself.

**Comment by QraveX** [comment]
Ive had the same issue, but ive tried it on several servers in different locations around the US and it still has uncontrollable lag and its unplayable.

I downloaded from both the website and ATLauncher and both had the same issue.

**Comment by WTFGeeks** [comment]
There's not a great deal I can suggest I'v set up many servers and not had any issues all running smoothly. The only thing that mite help is taking fastcraft of the server side and leaving it on the client instead of both. I'v not seen a problem with it on both but I'v heard a few who use it in different modpacks have, mite be worth a shot.
