### ISSUE TITLE
Why was Biomes O' Plenty removed?

### ISSUE THREAD

**Issue by MidoriMushrooms** [WTFGeeks/Natural-Magic#126]
Checked the changelog, couldn't find it for any version below 0.7.2.1 so it must have been removed before that. It was there for 0.6.3

The world seems bland without it. ):

**Comment by WTFGeeks** [comment]
It was removed a long time back yes, the reason was because I was having constant issues with it related to structure generation across multiple mods taking a large amount of dev time to sort out, none of these issues where game breaking but kept popping up.  Feel free to add it back in if you like I doubt it would cause to much of a problem but I wont be adding it back in as the time spent fixing all it's problems isn't worth it. Obviously as it's not in the pack though I wont be offering any support to those that have issues with it.
