### ISSUE TITLE
Quicksand- Artifacts

### ISSUE THREAD

**Issue by bajnaofdeath** [WTFGeeks/Natural-Magic#134]
I fell into a pool of quicksand from a mod called "Artifacts". I was digging myself out when I noticed that it sounded like I was taking damage but I was still at full health. Now Im stuck and I cant get out. I also tried placing blocks and using the /home command but it doesnt work. Tried logging out and in again but  it didnt help.

**Comment by BronyfromOz** [comment]
That's no issue.  Quicksand is really annoying.  Just keep digging and you'll get out eventually.

**Comment by bajnaofdeath** [comment]
I know its annoying but its not like ordinary quicksand. It seems to be a glitch or something because Ive been digging to the point where my shovel broke and I can still move around in it, quite fast actually, also the quicksand looks wierd.

![2015-01-04_15 08 52](https://cloud.githubusercontent.com/assets/10384485/5606211/d1d7d236-9423-11e4-854d-809a25313357.png)

**Comment by BronyfromOz** [comment]
Yup, that's quicksand. Did you not try to dig out the side of it?  If you try to dig out just the moving sands you could end up breaking a diamond shovel.

**Comment by ArcticHowler** [comment]
You can dig it out with fist and actually collect it if the "block" is full enough... it acts like a liquid and when you're close to the bottom of the top block you can also jump to get above the current block... suggestion: dig a piece of dirt from the edge while directly next to it so that you can slip out and quickly jump to a nearby "safe zone"(anywhere the quicksand wont flow to, aka 1 block above said opening) if timed right you'll be free of the quicksand... basically spam that jump button...

**Comment by bajnaofdeath** [comment]
Thanks! Finally out! Got knocked out by a skeleton and then knocked back in by a spider before I finally got out.
