### ISSUE TITLE
(Thaumic exploration) Creative menu crash

### ISSUE THREAD

**Issue by ghost** [WTFGeeks/Natural-Magic#35]
Decided to take a look at the modpack's contents and it wound up crashing when I tried to click the "Thaumic Explorer" creative tab. Checking the error message, it turned out to be a ClassNotFoundException: thaumcraft.common.lib.Utils

I did a quick check of the mods there, and lo and behold the base mod it's dependent on isn't there. I even looked at the modlists for installing in the ATLauncher and couldn't find it. I'm not sure if it's actually missing or somebody just forgot to get rid of the add-ons when getting rid of Thaumcraft.

**Comment by WTFGeeks** [comment]
The game will not load if Thaumcraft is not present, that's basic add-on mechanics. The error is due to the resent batch of Thaumcraft updates, a load of the add-ons are having a few issues with this TX has just had a update to fix all of these problems, it will be pushed in the next Natural Magic update.
