### ISSUE TITLE
Problem with connecting after claiming reward with Quest Book.

### ISSUE THREAD

**Issue by ICutStuff1** [WTFGeeks/Natural-Magic#44]
Others can still connect to server after claiming reward.

**Comment by xFlameAngel** [comment]
This has been addressed in previous issues, it is not optimized for a server yet and some major bugs are present, the current server available (because the AT launcher automatically compiles based on a set of rules WTFGeeks hasn't yet been able to optimize) does not work, please refer to https://github.com/WTFGeeks/Natural-Magic/issues/7 for more information on the current status!

**Comment by WTFGeeks** [comment]
This is now fixed in v0.7 please report back to me if you have anymore issues. bear in mine 0.7 will require a world restart as it's a fairly large update.
