### ISSUE TITLE
[Magical Crops] Aluminium Seeds 

### ISSUE THREAD

**Issue by MinoForge** [WTFGeeks/Natural-Magic#54]
Aluminium seeds are uncraftable(while copper, tin are).
Cheated some in, and they grow just fine. Aluminium essence does not craft into anything. Is this intended, and if so, why are Copper, Tin, not like this?

**Comment by kiomadoushi** [comment]
I play this SSP, but I also play Sky Factory with a friend (SMP and CMP); there, the seeds are craftable (uses strong essence). I actually first thought you might've been trying the wrong recipe, sorry, but I can't find one that works for them either...

I doubt it's intended, unless WTFGeeks purposely disabled their recipe (if so, why? it's not like having aluminum seeds breaks the pack). I bet there's just some conflict with the mods in the pack because they also don't have an EMC value.

**Comment by BronyfromOz** [comment]
I'm not finding recipes for Cobalt or Ardite seeds.  Maybe the tinkers stuff has been disabled.

**Comment by kiomadoushi** [comment]
Aren't copper and tin part of the tinker's group too? Why are they craftable, but those not?

But if it's more than one seed, it's likely intentionally disabled...

**Comment by BronyfromOz** [comment]
Copper and Tin essence generate Ore from Forestry pack.  Guess all tinkers have been disabled.

**Comment by MinoForge** [comment]
Ahh, that makes sense. Now we know /what/ is going on. But the question still stands. Intended?

**Comment by WTFGeeks** [comment]
So if you look inside the magic crops config you'll notice there is no way to disable or enable certain seed types. how Magic crops works is on startup it checks to see what mods you have installed and if it has a seed type for that mod it will enable it, weirdly for the new tinkers construct it was not recognising it as installed, bearing in mind magic crops is still in beta for 1.7.10 these type of things are bound to crop up.  For now I have added the recipes my self via minetweaker and the essence recipes for cobalt, ardite and aluminium, this is available in v0.7.
