### ISSUE TITLE
Lycanite's Mobs - Spawning too much

### ISSUE THREAD

**Issue by Frozen4977** [WTFGeeks/Natural-Magic#66]
Raikos are spawning a lot, and I do mean A LOT.
About 100 in a small area.
Other mobs seem fine so far.

**Comment by xFlameAngel** [comment]
I can attest to this but my problem is with pretty much EVERY single Lycanites mob, I have a massive lag problem with my base, managed to work my way up to a shard of laputa XX and built a bse in the sky, the rocs are unbearable, cant build near water because of jinyu's, theres just too many mobs in general now, even on my high end pc im finding the lag from having over 200 entities rendered at any one time unbearable

**Comment by ArcticHowler** [comment]
I practically have to play in peaceful which seems to be default because of how many mobs spawn now, and 0 native mobs seem to spawn(in easy/normal) now because of these new guys which makes the quest book impossible to 100% complete, well 100% of what was/is working anyways...

**Comment by WTFGeeks** [comment]
Just updated to 0.7.1 I totally derped and forgot to add all the config changes for spawn amounts for Lycanites. That should solve all your issues.
