### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by ToTheMaxHD** [WTFGeeks/Natural-Magic#69]
I saw Biomes O' Plenty and TreeCapitator were removed, do you plan to re-add them once you can make them work together or are they out for good?

**Comment by WTFGeeks** [comment]
Biomes O Plenty will not be added back in, feel free to add it yourself if you want it'll probably work, but I'm constantly having to fight small bugs and crashes every time I do updates with it due to so many of the mods evolving around worldgen and while the BoP guys are focused on 1.8 more issues seem to be cropping up. As for treecapitator I only dropped it as veinminer does the same thing, there was no problem with it I just see no point in having 2 mods that do the same thing.

**Comment by ToTheMaxHD** [comment]
Okay, thanks, and I think there are a few other mods similar to BoP that may work better, worth a shot looking in to anyway
