### ISSUE TITLE
Invisible Blocks in 0.7.1 version of Natural Magic

### ISSUE THREAD

**Issue by SamuelX16** [WTFGeeks/Natural-Magic#72]
I have notice that all Botania plants are invisible expect for the particle effects and tinkers construct work bench in its first form is invisible.

**Comment by WTFGeeks** [comment]
Hi sorry I'v never heard of that problem before, did you do the world restart and have that problem from the get go? could you possibly send me a screenshot please, I'v tested a load of worlds and never came across that. Also do you have any additional mods installed you have added or resource packs?

**Comment by Leekit** [comment]
In addition to these problems all the Chisel blocks are glitched the same way and there are several things in Thaumcraft that have invisible textures like all the ores, essentia pipes, the crucible, the arcane lamp and it's counterparts, etc. Not sure about the Thaumcraft add-ons.

**Comment by Lankoran** [comment]
Hmmm I've not seen this i've got to be honest, i'm running the default pack, no additions only Hats removed with the John Smiths texture pack. And all of the above mentioned blocks are visible for me at least.

**Comment by Leekit** [comment]
That might be due to your texture pack though. I play in default and the textures are screwy for me.

**Comment by Rosegrave** [comment]
I just ran the update for the mod pack. Looking through all the items available, the ones that got trashed are totally invisible and no longer have their mod name or icon - it's just baser coding and a blank space where the icon should be. Carpenter's Blocks, Twilight Forest, Botania, and Forestry seem to have been hit the worst. In-game, the affected blocks are either invisible or totally missing from the world. I do use Sphax 16x as a resource pack and tried downgrading to straight Vanilla to see if it was a support issue - it's not. The only mod I had added was OptiFine so that my computer could run at a halfway decent pace (it's a bit special). I also tried patching in a new instance on a different system with only the core mods and resource packs and the same problem occurred. Of course, I didn't read the stupid thing, but post-update yesterday and today (I was prompted to update twice for some reason) I got an in-game warning. Yesterday it informed me that Forge couldn't recall some 700 blocks and proceeding would see them erased. I thought nothing of it because my world hadn't been effected at all. Post-update today, I got the same warning in excess of 900 blocks and I could pretty much see to the core of the earth through my house. I reinstalled the instance through the AT Launcher _again_ on a whim and everything is sorta back to normal. There's no invisible blocks and my Trees of Transformation have their canopies back, but the Forestry and Botania elements are still totally missing. Some texture support on Sphax is also MIA, as the glowstone is back to its Vanilla self.

**Comment by WTFGeeks** [comment]
Did you do what the Warning message said when you updated the pack? from 0.6.3 to 0.7+

**Comment by Gigalamesh** [comment]
It seems to be that OptiFine has some issue rendering certain blocks. When I disabled it, everything seemed to be showing up fine. I haven't tested previous OptiFine versions, but I would assume they have the same issue.

**Comment by Leekit** [comment]
Gigalmesh is correct. I believe it was an Optifine issue. I disabled it and it was normal again.

**Comment by SamuelX16** [comment]
Sorry my mistake it was optifine that was causing the issue and maybe my ExtraTic mod. But I believe it was just optifine.

**Comment by Rosegrave** [comment]
OptiFine doesn't seem to be the heart of the matter in my neck of the woods. I've created a new instance with _only_ core mods enabled, using the default resource pack, and I'm still missing a large majority of the items that should be available. Botania, Carpenter's Blocks, Natura... basically everything listed previously is totally MIA. I'm aware that the world I had from the previous version is kaput because 6.3 and 0.7 don't communicate with one another. However, I'm trying to start 0.7 worlds and it's the _same problem_. Can _someone_ think of anything _else_ that could be wrong because I'm about to embark upon the very, very tedious task of rolling back the update just so I can play.

**Comment by eushwa** [comment]
You could try downgrading to forge 1232, just download that version and replace the one in the jarmods folder.
