### ISSUE TITLE
[Request] Chunk Loaders?

### ISSUE THREAD

**Issue by Lankoran** [WTFGeeks/Natural-Magic#74]
Hi Lewis, I'll be honest, i was a little cross about BoP being pulled, but i'll forgive you due to Beta, and decided to continue with 0.7.1, which seems to be quite cool so far, does miss BoP though, vanilla MC will never be as good as BoP. Personal opinion of course!.

anyway, i was wondering if you'd consider adding a chunk loading mod to the pack in your future updates, if at all?, they aren't really required i know, but it'd be nice to have one, the only one i'm aware of is the poppet shelf from Witchery. But don't want to over-use them. Just feel in a pack that encourages you to go out traveling and exploring, it'd be nice to know that your crops at home, especially mana bean farms continue to thrive. Anyway hope your brilliant and have yourself a great day as always! :D

**Comment by WTFGeeks** [comment]
Hi Lankoran, to be honest I didn't want to pull BoP either but the amount of issues it was causing me was massive, it seems mods are updating but BoP is falling behind as they are focusing on 1.8 and that's where the issue is. As far as chunk loading I'm considering adding chicken chunks as a optional mod for those that wish to use it, I'v always stayed away from chunk loading favouring performance but I think making it optional then gives the user the option if they would like it. If it plays well I'll add it in the next update.
