### ISSUE TITLE
Server crash causes alchmical bags and transmutation table reset

### ISSUE THREAD

**Issue by Enolamron** [WTFGeeks/Natural-Magic#94]
Running 0.7.2 server
Someone already posted it on the projecte tracker and this was the response.

"This was fixed in 0.2D-DEV2
I recommend using the dev versions currently as they have MANY bug fixes. The only issue is dev builds need thaumcraft installed on the client for the game to launch until a new dev build comes out.

EDIT: 0.2D DEV10 fixed the thaumcraft issue. You should update to it!"

I learned the hard way and figured I would clean up all my chests in my table and then I get the blockling crash again and after the server auto restarted I found all my taught items are gone. Back to square one again building up 100's of items

**Comment by WTFGeeks** [comment]
Thanks for pointing out the project E fixes, but this does not solve the root of the issue. Why did you crash in the first place for the items to reset? was it due to removing Blocklings and getting a crash? if so you do understand HQM maps are specifically made to not have mods removed as that will break the pack, or was Blocklings crashing before you tried removing it?

**Comment by Enolamron** [comment]
The crash was with no mods removed. I made a new issue for the blockling crash

**Comment by WTFGeeks** [comment]
As for the Project E issue I'm going to have a play around with the beta version first before adding it in, it looks like all current in game project E items will be wiped, according to the project e dev this will take place sooner or later anyway so either way its going to happen, but I would like to test it first.
